
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: docker-elasticsearch

# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
http.port: 9200

# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
#action.destructive_requires_name: true
#http.cors.allow-origin: "/.*/"
#http.cors.enabled: true
#network.bind_host: 0.0.0.0
#node.master: true
#node.data: true
#transport.host: localhost
#transport.tcp.port: 9300
