version: '2.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - type: bind
        source: ./elasticsearch/data
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - ebk
    deploy:
      mode: replicated
      replicas: 1

  filebeat:
    image: store/elastic/filebeat:7.10.1
    user: root
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - type: bind
        source: ./filebeat/data
        target: /usr/share/filebeat/data
      - type: bind
        source: ./filebeat/modules.d/
        target: /usr/share/filebeat/modules.d/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/log/
        target: /var/log/
        read_only: true
    networks:
      - ebk
  
  metricbeat:
    image: store/elastic/metricbeat:7.10.1
    configs:
      - source: metricbeat_config
        target: /usr/share/metricbeat/metricbeat.yml
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
    networks:
      - ebk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - ebk
    deploy:
      mode: replicated
      replicas: 1

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  filebeat_config:
    file: ./filebeat/config/filebeat.yml
  metricbeat_config:
    file: ./metricbeat/config/metricbeat.yml
  kibana_config:
    file: ./kibana/config/kibana.yml

networks:
  ebk:
    driver: bridge