# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601
server.host: "0.0.0.0"
server.name: "docker-kibana"

# The URLs of the Elasticsearch instances to use for all your queries.
elasticsearch.hosts: ["http://0.0.0.0:9200"]

monitoring.ui.container.elasticsearch.enabled: true

#elasticsearch.username: "admin"
#elasticsearch.password: "admin"

logging.quiet: true

